// GENERATED by `pnpm --filter @elections-tracker/worker baseline:export` —
// do not edit by hand. Percentiles of the pooled daily high-risk-pivotal
// counts across every corrected historical baseline (§43): each cycle's
// final-100-day replay contributes one observation per day. The threat
// scale is defined against this distribution, so a level always means
// "relative to where past cycles actually sat," not an invented constant.
export const THREAT_CALIBRATION = {
  generatedAt: "2026-08-22",
  methodologyVersion: "2026.09.4",
  cycles: [2016, 2018, 2020, 2022, 2024],
  observations: 505,
  // Cutpoints on the pooled distribution.
  p50: 51,
  p90: 84,
  max: 103,
} as const;

export type ControlThreat = "LOW" | "MODERATE" | "HIGH" | "UNKNOWN";

// LOW: below the historical median cycle-day. MODERATE: in the upper half
// of the historical range. HIGH: above the 90th percentile — beyond nearly
// every cycle-day any corrected baseline recorded. UNKNOWN is the caller's
// job (no assessed races = no basis for a call).
export function controlThreatLevel(highRiskPivotal: number): ControlThreat {
  if (highRiskPivotal >= THREAT_CALIBRATION.p90) return "HIGH";
  if (highRiskPivotal >= THREAT_CALIBRATION.p50) return "MODERATE";
  return "LOW";
}
